name: Generate and Publish Docs
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install npm 9
        run: npm install -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: Build all package assets
        run: npm run build --workspace=packages

      - name: Generate docs
        run: npm run docs

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "--recursive --whole-file --delete --verbose"
          SOURCE: "api/"
          TARGET: "/var/www/html/cefn.com/lauf/api/"
